movement_patterns:
  - type: linear
    x: 1.0
    y: 0.0
    duration: 2.0
  - type: linear
    x: 0.0
    y: 1.0
    duration: 2.0
  - type: diagonal
    x: 1.0
    y: 1.0
    duration: 3.0
  - type: rotation
    z: 1.0
    duration: 2.0